version: '3'
services:
  web:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
     - "80:80"
    links:
     - app
  app:
    container_name: tomcat
    build: .
    restart: always
    ports:
     - "8080:8080"
    links:
     - dbserver
  dbserver:
    build: ./mysql
    container_name: mysql
    restart: always
    ports:
     - "3306:3306"
    volumes:
      - /home/clouder245/mysql/:/var/lib/mysql/
