apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dbserver
  name: dbserver
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: dbserver
  type: ClusterIP
status:
  loadBalancer: {}
